version: 2

project_name: go-htmx-templ-tailwind

before:
  hooks:
  - templ generate
  - tailwindcss -i static/css/input.css -o static/css/style.css --minify
  - go mod tidy
  - go generate ./...

builds:
- id: go-htmx-templ-tailwind
  env:
  - CGO_ENABLED=0
  goos: [ linux ]
  goarch: [ arm64 ]
  binary: 'go-htmx-templ-tailwind'
  ldflags:
  - -w
  - -s

kos:
- build: go-htmx-templ-tailwind
  repository: 'ghcr.io/laubi/go-htmx-templ-tailwind'
  bare: true
  platforms:
  - 'linux/arm64'
  - 'linux/amd64'
  tags:
  - "{{.Version}}"
  labels:
    org.opencontainers.image.source: "https://github.com/Laubi/go-htmx-templ-tailwind"

archives:
- format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
  name_template: >-
    {{ .ProjectName }}_
    {{- tolower .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - "^docs:"
    - "^test:"
