apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-htmx-templ-tailwind
  labels:
    app.kubernetes.io/name: go-htmx-templ-tailwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-htmx-templ-tailwind
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-htmx-templ-tailwind
    spec:
      containers:
      - name: go-htmx-templ-tailwind
        image: ghcr.io/laubi/go-htmx-templ-tailwind:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: '8080'
        ports:
        - containerPort: 8080
          name: web
        readinessProbe:
          httpGet:
            port: web
            path: /
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: go-htmx-templ-tailwind
  labels:
    app.kubernetes.io/name: go-htmx-templ-tailwind
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    nodePort: 30321
    targetPort: web
  selector:
    app.kubernetes.io/name: go-htmx-templ-tailwind
  sessionAffinity: ClientIP
