name: Integration

on:
  push:

permissions:
  contents: write

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        cache: true

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Generate templ files
      run: templ generate

    - name: Tests
      run: go test ./...

    - name: Vet
      run: go vet ./...
