name: Release

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        cache: true

    - name: Install templ
      run: |
        go install github.com/a-h/templ/cmd/templ@latest

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name:  Install Tailwind CLI
      run: npm install -g tailwindcss postcss autoprefixer

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dry-run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      if: "!startsWith(github.ref, 'refs/tags/v')"
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
